properties:
  managedEnvironmentId: /subscriptions/c31a467b-0b00-4347-a9ce-5d1bac3ff56a/resourceGroups/KLC/providers/Microsoft.App/managedEnvironments/managedEnvironment-KLC-965e
  configuration:
    ingress:
      external: true
      allowInsecure: false
      targetPort: 8080
  template:
    containers:
      - env:
          - name: DATABASE_URL
            secretRef: db-url
          - name: GOOGLE_CLIENT_ID
            value: 362406102359-frmsjn6et0551pciju1li4mep62thmse.apps.googleusercontent.com
          - name: SMTP_SERVER
            value: smtp.gmail.com
          - name: SMTP_USERNAME
            value: bookings@kathielambcentre.org
          - name: SMTP_PASSWORD
            secretRef: smtp-password
          - name: GOOGLE_RECAPTCHA_SECRET
            secretRef: google-recaptcha-secret
          - name: OTEL_SERVICE_NAME
            value: district
          - name: OTEL_EXPORTER_OTLP_PROTOCOL
            value: http/protobuf
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: https://api.honeycomb.io
          - name: OTEL_EXPORTER_OTLP_HEADERS
            secretRef: honeycomb-otlp-header
        image: ghcr.io/girlguidingstaplehurst/district:v0.2.1
        imagePullPolicy: IfNotPresent
        name: district
        ports:
          - containerPort: 8080
            protocol: TCP
        resources:
          cpu: '0.5'
          memory: 1Gi
