// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package rest

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gofiber/fiber/v2"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Send a contact us message
	// (POST /api/v1/contact-us)
	ContactUs(c *fiber.Ctx) error
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

type MiddlewareFunc fiber.Handler

// ContactUs operation middleware
func (siw *ServerInterfaceWrapper) ContactUs(c *fiber.Ctx) error {

	return siw.Handler.ContactUs(c)
}

// FiberServerOptions provides options for the Fiber server.
type FiberServerOptions struct {
	BaseURL     string
	Middlewares []MiddlewareFunc
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router fiber.Router, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, FiberServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router fiber.Router, si ServerInterface, options FiberServerOptions) {
	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	for _, m := range options.Middlewares {
		router.Use(fiber.Handler(m))
	}

	router.Post(options.BaseURL+"/api/v1/contact-us", wrapper.ContactUs)

}

type ContactUsRequestObject struct {
	Body *ContactUsJSONRequestBody
}

type ContactUsResponseObject interface {
	VisitContactUsResponse(ctx *fiber.Ctx) error
}

type ContactUs200Response struct {
}

func (response ContactUs200Response) VisitContactUsResponse(ctx *fiber.Ctx) error {
	ctx.Status(200)
	return nil
}

type ContactUs422JSONResponse ErrorResponse

func (response ContactUs422JSONResponse) VisitContactUsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(422)

	return ctx.JSON(&response)
}

type ContactUs500JSONResponse ErrorResponse

func (response ContactUs500JSONResponse) VisitContactUsResponse(ctx *fiber.Ctx) error {
	ctx.Response().Header.Set("Content-Type", "application/json")
	ctx.Status(500)

	return ctx.JSON(&response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Send a contact us message
	// (POST /api/v1/contact-us)
	ContactUs(ctx context.Context, request ContactUsRequestObject) (ContactUsResponseObject, error)
}

type StrictHandlerFunc func(ctx *fiber.Ctx, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ContactUs operation middleware
func (sh *strictHandler) ContactUs(ctx *fiber.Ctx) error {
	var request ContactUsRequestObject

	var body ContactUsJSONRequestBody
	if err := ctx.BodyParser(&body); err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	}
	request.Body = &body

	handler := func(ctx *fiber.Ctx, request interface{}) (interface{}, error) {
		return sh.ssi.ContactUs(ctx.UserContext(), request.(ContactUsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ContactUs")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return fiber.NewError(fiber.StatusBadRequest, err.Error())
	} else if validResponse, ok := response.(ContactUsResponseObject); ok {
		if err := validResponse.VisitContactUsResponse(ctx); err != nil {
			return fiber.NewError(fiber.StatusBadRequest, err.Error())
		}
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xTT1PbPhD9Kpr9/Y7CDtBefKOFMnTawhBoDx2GEfLGFmNLqrQmzTD+7p2VHNKQ9Nbp",
	"Kcr+efv2+e0zaNd7Z9FShOoZom6xV+n53llSmm7jZ4xRNcgxH5zHQAZTBfbKdPxYuNArgmqKSKCVR6gg",
	"UjC2gVFCv8HYyVnV70uMEgL+GEzAGqrvuUq+TFgD3r0Mcw+PqIkBz0Jw4Rqjdzbuo83p+z8zejV4u3x3",
	"3ighoh6CodWc1ctDVN0be68GavnfA6qA4cNapo/fbkBmrRkpZzeytUQeRgY2duG4v8aog/FknIUKbi5P",
	"L0FCZzROC2YJ4fzLrThZLDA4cX71SRwXM5AwhG7CjFVZLpfLorFD4UJTTgCxVI3vDo6LWYG2aKnvWEQy",
	"1DHmqWFdNImTqwuQ8IQhZhaHxayYcaXzaJU3UAFDHIMEr6hNKpTKm/LpsNTZSwdDinoXiX/5oyje6aKG",
	"auM3yPpjpHeuXnEht6NNPcr7zujUVT5GJrI2Lb/+D7iACv4rN64uJ0uXO35OCm8ru0797gAKAyZLZD+l",
	"DY5ms93PMh+0xhgXQ9etRGS+o4Q3R0d/bYNtX++h/1V1pk7IAn9qzOFRwttM99+QmLseqTW2EUu0JJbB",
	"TUcVh75XYcUlaGuhxOQKMUTRvwhPqol8dn546IyGuzRhCr5W/CrViOuz+Q3bk50zXcLUPcqdlmCeFKE4",
	"4ftka2e59kCkC4bxbvwVAAD//+MNBKMkBQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
