// Package rest provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package rest

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	Admin_authScopes = "admin_auth.Scopes"
)

// Defines values for DiscountTableRowType.
const (
	Flat DiscountTableRowType = "flat"
)

// Defines values for EventStatus.
const (
	EventStatusApproved          EventStatus = "approved"
	EventStatusAwaitingDocuments EventStatus = "awaiting documents"
	EventStatusCancelled         EventStatus = "cancelled"
	EventStatusProvisional       EventStatus = "provisional"
)

// Defines values for InvoiceStatus.
const (
	InvoiceStatusCancelled InvoiceStatus = "cancelled"
	InvoiceStatusPaid      InvoiceStatus = "paid"
	InvoiceStatusRaised    InvoiceStatus = "raised"
)

// AdminEventList defines model for AdminEventList.
type AdminEventList struct {
	Events []Event `json:"events"`
}

// AdminNewEvents defines model for AdminNewEvents.
type AdminNewEvents struct {
	Contact struct {
		EmailAddress openapi_types.Email `json:"email_address"`
		Name         string              `json:"name"`
	} `json:"contact"`
	Event struct {
		Details         string          `json:"details"`
		Instances       []EventInstance `json:"instances"`
		Name            string          `json:"name"`
		PubliclyVisible bool            `json:"publicly_visible"`
		Rate            string          `json:"rate"`
		Status          string          `json:"status"`
	} `json:"event"`
}

// Contact defines model for Contact.
type Contact struct {
	EmailAddress openapi_types.Email `json:"email_address"`
	Name         string              `json:"name"`
}

// DiscountTable defines model for DiscountTable.
type DiscountTable map[string]DiscountTableRow

// DiscountTableRow defines model for DiscountTableRow.
type DiscountTableRow struct {
	Type  DiscountTableRowType `json:"type"`
	Value float32              `json:"value"`
}

// DiscountTableRowType defines model for DiscountTableRow.Type.
type DiscountTableRowType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	ErrorMessage string `json:"error_message"`
}

// Event defines model for Event.
type Event struct {
	Assignee     *openapi_types.Email `json:"assignee,omitempty"`
	Contact      string               `json:"contact"`
	Details      string               `json:"details"`
	Email        openapi_types.Email  `json:"email"`
	From         string               `json:"from"`
	Id           string               `json:"id"`
	Invoices     *[]InvoiceRef        `json:"invoices,omitempty"`
	KeyholderIn  *openapi_types.Email `json:"keyholderIn,omitempty"`
	KeyholderOut *openapi_types.Email `json:"keyholderOut,omitempty"`
	Name         string               `json:"name"`
	RateID       string               `json:"rateID"`
	Status       EventStatus          `json:"status"`
	To           string               `json:"to"`
	Visible      bool                 `json:"visible"`
}

// EventDetails defines model for EventDetails.
type EventDetails struct {
	Details         string `json:"details"`
	From            string `json:"from"`
	Name            string `json:"name"`
	PubliclyVisible bool   `json:"publicly_visible"`
	To              string `json:"to"`
}

// EventInstance defines model for EventInstance.
type EventInstance struct {
	From string `json:"from"`
	To   string `json:"to"`
}

// EventList defines model for EventList.
type EventList struct {
	Events []ListEvent `json:"events"`
}

// EventStatus defines model for EventStatus.
type EventStatus string

// Invoice defines model for Invoice.
type Invoice struct {
	Contact   openapi_types.Email `json:"contact"`
	Id        string              `json:"id"`
	Items     []InvoiceItem       `json:"items"`
	Paid      *string             `json:"paid,omitempty"`
	Reference string              `json:"reference"`
	Sent      *string             `json:"sent,omitempty"`
	Status    InvoiceStatus       `json:"status"`
}

// InvoiceEvent defines model for InvoiceEvent.
type InvoiceEvent struct {
	DiscountTable DiscountTable `json:"discountTable"`
	From          string        `json:"from"`
	Id            string        `json:"id"`
	Name          string        `json:"name"`
	Rate          float32       `json:"rate"`
	Status        EventStatus   `json:"status"`
	To            string        `json:"to"`
}

// InvoiceEvents defines model for InvoiceEvents.
type InvoiceEvents map[string][]InvoiceEvent

// InvoiceItem defines model for InvoiceItem.
type InvoiceItem struct {
	Cost        float32 `json:"cost"`
	Description string  `json:"description"`
	EventID     *string `json:"eventID,omitempty"`
	Id          *string `json:"id,omitempty"`
}

// InvoiceRef defines model for InvoiceRef.
type InvoiceRef struct {
	Id        string        `json:"id"`
	Paid      *string       `json:"paid,omitempty"`
	Reference string        `json:"reference"`
	Sent      *string       `json:"sent,omitempty"`
	Status    InvoiceStatus `json:"status"`
}

// InvoiceStatus defines model for InvoiceStatus.
type InvoiceStatus string

// ListEvent defines model for ListEvent.
type ListEvent struct {
	From   string      `json:"from"`
	Id     string      `json:"id"`
	Name   string      `json:"name"`
	Status EventStatus `json:"status"`
	To     string      `json:"to"`
}

// NewEvent defines model for NewEvent.
type NewEvent struct {
	Adhesives         bool         `json:"adhesives"`
	CaptchaToken      string       `json:"captchaToken"`
	CarParking        bool         `json:"carParking"`
	CleaningAndDamage bool         `json:"cleaningAndDamage"`
	Contact           Contact      `json:"contact"`
	Event             EventDetails `json:"event"`
	PrivacyPolicy     bool         `json:"privacyPolicy"`
	TermsOfHire       bool         `json:"termsOfHire"`
}

// Rate defines model for Rate.
type Rate struct {
	Description   string                  `json:"description"`
	DiscountTable *map[string]interface{} `json:"discountTable,omitempty"`
	HourlyRate    float32                 `json:"hourlyRate"`
	Id            string                  `json:"id"`
}

// RatesList defines model for RatesList.
type RatesList = []Rate

// RequestDocumentsBody defines model for RequestDocumentsBody.
type RequestDocumentsBody struct {
	CoshhSheets     bool `json:"coshhSheets"`
	DbsCertificate  bool `json:"dbsCertificate"`
	FoodSafety      bool `json:"foodSafety"`
	PublicLiability bool `json:"publicLiability"`
	RiskAssessment  bool `json:"riskAssessment"`
}

// SendInvoiceBody defines model for SendInvoiceBody.
type SendInvoiceBody struct {
	Contact openapi_types.Email `json:"contact"`

	// Events List of Event IDs that this invoice applies to.
	Events *[]string             `json:"events,omitempty"`
	Items  []SendInvoiceBodyItem `json:"items"`
}

// SendInvoiceBodyItem defines model for SendInvoiceBodyItem.
type SendInvoiceBodyItem struct {
	Cost        float32 `json:"cost"`
	Description string  `json:"description"`
	EventID     *string `json:"eventID,omitempty"`
}

// SetRateBody defines model for SetRateBody.
type SetRateBody struct {
	Rate string `json:"rate"`
}

// GetApiV1AdminEventsParams defines parameters for GetApiV1AdminEvents.
type GetApiV1AdminEventsParams struct {
	// From The date to obtain events from
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To The date to obtain events to
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`

	// Contact Optional filter to events for a specific contact. Value is the contact's email.
	Contact *string `form:"contact,omitempty" json:"contact,omitempty"`
}

// AdminGetInvoicesForEventsParams defines parameters for AdminGetInvoicesForEvents.
type AdminGetInvoicesForEventsParams struct {
	// Events A comma-separated list of events to generate invoices for
	Events []string `form:"events" json:"events"`
}

// GetApiV1EventsParams defines parameters for GetApiV1Events.
type GetApiV1EventsParams struct {
	// From The date to obtain events from
	From *openapi_types.Date `form:"from,omitempty" json:"from,omitempty"`

	// To The date to obtain events to
	To *openapi_types.Date `form:"to,omitempty" json:"to,omitempty"`
}

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = NewEvent

// AdminAddEventsJSONRequestBody defines body for AdminAddEvents for application/json ContentType.
type AdminAddEventsJSONRequestBody = AdminNewEvents

// AdminEventRequestDocumentsJSONRequestBody defines body for AdminEventRequestDocuments for application/json ContentType.
type AdminEventRequestDocumentsJSONRequestBody = RequestDocumentsBody

// AdminEventSetRateJSONRequestBody defines body for AdminEventSetRate for application/json ContentType.
type AdminEventSetRateJSONRequestBody = SetRateBody

// AdminSendInvoiceJSONRequestBody defines body for AdminSendInvoice for application/json ContentType.
type AdminSendInvoiceJSONRequestBody = SendInvoiceBody
