apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: db-url
spec:
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore

  data:
    - secretKey: url
      remoteRef:
        key: db-url