apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: recaptcha-secret
spec:
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore

  data:
    - secretKey: recaptcha-secret
      remoteRef:
        key: google-recaptcha-secret