apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: smtp-password
spec:
  secretStoreRef:
    name: azure-backend
    kind: ClusterSecretStore

  data:
    - secretKey: smtp-password
      remoteRef:
        key: smtp-password