// Code generated by MockGen. DO NOT EDIT.
// Source: server.go
//
// Generated by this command:
//
//	mockgen -source server.go -destination mock/server.go
//

// Package mock_rest is a generated GoMock package.
package mock_rest
