openapi: 3.0.3
info:
  title: District API
  description: |-
    TODO
  license:
    name: GNU Affero GPL 3.0
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 1.0.0
tags:
  - name: public
    description: Public REST APIs
  - name: admin
    description: Private Administration REST APIs
paths:
  /api/v1/contact-us:
    post:
      tags:
        - public
      summary: Send a contact us message
      operationId: contactUs
      requestBody:
        description: Message
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContactUsMessage'
        required: true
      responses:
        '200':
          description: Successfully sent
        '422':
          description: Validation exception
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Something went wrong
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - error_message
      properties:
        error_message:
          type: string
    ContactUsMessage:
      type: object
      required:
        - name
        - email
        - message
      properties:
        name:
          type: string
        email:
          type: string
          format: email
        message:
          type: string
  securitySchemes:
    admin_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT